<?php
	/* Includes */
    include("include/simple_html_dom.php");
    
    /* Constants */
    $BASE_PLAYLIST_URL = "https://embed.spotify.com/?uri=";
    $BASE_TRACK_URL = "http://open.spotify.com/track/";
    
    /* Settings */
    $the_uri = "spotify:user:tkndk:playlist:3kVvQq7ZECq0PAj4Ue9n9u"; //"spotify:user:ulyssestone:playlist:2D50pNwa1xmbiUhqM6KDiG";
        
    /* Functions */
	function get_uri($track_html) {
        $uri = explode(' ', $track_html->find("li",1)->class);
        return $uri[1];
    }
    
    function get_title($track_html) {
        $title = explode(' ', $track_html->find("li",1)->plaintext, 2);
        return $title[1];
    }
    
    function get_artist($track_html) {
        return $track_html->find("li",2)->plaintext;
    }
    
    /* The Action */
    $the_playlist_url = $BASE_PLAYLIST_URL.$the_uri;
    $the_playlist_html = file_get_html($the_playlist_url);
    $the_tracks_html = $the_playlist_html->find('ul[class=track-info]');
    
    foreach($the_tracks_html as $track) {
        $the_track['uri'] = get_uri($track);
        $the_track['title'] = get_title($track);
        $the_track['artist'] = get_artist($track);
        $the_tracks[] = $the_track;
    }

    //echo count($the_tracks);
    //print_r($the_tracks);

	/* The Output */
	echo '<?xml version="1.0" encoding="UTF-8" ?>';
	echo '<rss version="2.0">';
	echo 	'<channel>';
	echo 		'<title>'.$the_playlist_html->find('title',0)->plaintext.'</title>';
	echo 		'<description>Spofity playlist feed generated by Spotifeed</description>';
	echo 		'<link>'.$the_playlist_url.'</link>';
	echo 		'<ttl>720</ttl>';

    if ($the_tracks) {
    	foreach($the_tracks as $track) {
        	echo "<item>";
        	echo 	"<title>".$track['title']."</title>";
        	echo 	"<description>".$track['artist']."</description>";
        	echo 	"<link>".$BASE_TRACK_URL.$track['uri']."</link>";
        	echo 	"<guid>".$track['uri']."</guid>";
        	echo 	"<pubDate>Mon, 06 Sep 2009 16:45:00 +0000 </pubDate>";
        	echo "</item>";
        }
    }
    
    echo 	'</channel>';
	echo '</rss>';
	
	/* The End :) */
?>